### ISSUE TITLE
Plant List

### ISSUE THREAD

**Issue by Bianca-Gundel** [Bianca-Gundel/RecapProject4#23]
# Plant List

## Value Proposition

**As a user**

**I want to** browse a list of plants,

**so that** I can discover new plants and learn about their care requirements.

## Description

Capstone Group Todo: Add wireframes

## Acceptance Criteria

- The homepage displays a list of plants.
- The plant list is headlined with its purpose.
- Each plant listing includes:
  - Plant name
  - Plant botanical name
  - Plant image
- The list supports vertical scrolling to accommodate multiple entries.

## Tasks

- [ ] Create feature branch `feature/plant-list`
- [ ] Inspect and adapt the example data in the [assets folder](./assets/plants.json)
  - [ ] Add an `imageUrl` for each plant, for example from [unsplash.com](unsplash.com)
- [ ] Capstone Group Todo: Add tasks
